### ISSUE TITLE
WebDAV Quotas support (RFC 4331)

### ISSUE THREAD

**Issue by yar229** [ramondeklein/nwebdav#5]
Is there any plans to implement this feature?
Thanks!

**Comment by ramondeklein** [comment]
I am currently focusing on more documentation for NWebDAV to improve the adoption rate of the library. I think the code quality is already high (IMHO), but without documentation it might still be hard to use (despite the sample applications).

Another focus is to make it 100% compliant with the WebDAV specification. High adoption rate will also improve compliance, so documentation is very important for me at this stage.

I am also working on more data stores. The first is the Azure BLOB storage store to allow NWebDAV to work with Azure BLOB storage. I think that an iTunes store would also be great to access the iTunes library as a drive (read-only).

Enabling quota support is also high on my wish-list, but it requires either support from the underlying storage technology or we should keep track of it using a plug-in module that uses some kind of database to keep track of the quota. I would prefer the latter, but it's a lot of work. Don't expect it within a few months.

**Comment by ramondeklein** [comment]
If you only need to support that `quota-available-bytes` property returns the amount of free disk-space for a collection, then I can add it pretty easily for the disk store.

**Comment by yar229** [comment]
Damn.. It's so simple. 
Thanks for fine interfaces and sorry for bothering you...

'''
    public class DavExtCollectionQuotaAvailableBytes<TEntry> : DavInt64<TEntry> where TEntry : IStoreItem
    {
        public static readonly XName PropertyName = WebDavNamespaces.DavNs + "quota-available-bytes";

        public override XName Name
        {
            get
            {
                return DavExtCollectionQuotaAvailableBytes<TEntry>.PropertyName;
            }
        }
    }
'''

**Comment by ramondeklein** [comment]
That's the proper way to define the properties, but you should also extend the properties in your store's collections and/or items to provide the logic to obtain the actual values. The disk store shows how to do this.

I have added the properties with documentation in commit 5fd4a7d251fef07061be3c6b8d8f0809ca4a1a96 (these changes haven't propagated to the NuGet package yet). Because there is no platform independent way to determine the free disk space and/or quota in .NET core, the disk store doesn't implement this functionality.
