### ISSUE TITLE
Maximum size of attributes

### ISSUE THREAD

**Issue by fiddyschmitt** [ramondeklein/nwebdav#70]
Hi Ramon,

When PROPFIND returns a large number of files (thousands), the Windows 10 WebDAV client doesn't display the folder.

The workaround is to increase `FileAttributesLimitInBytes`  registry setting from 1,000,000 bytes to something larger. But admin rights are required because the setting is in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters`

Do you know if the WebDAV standard supports sending back responses in smaller chunks?

As a last resort, I'll have to create a number of virtual subfolders, eg:
```
0 - 1,000
1,000 - 2,000
2,000 - 3,000
```

Thanks!
Fidel

**Comment by ramondeklein** [comment]
It's not possible to split the result, because `PROPFIND` returns an XML document and XML needs to be balanced with open and close tags. There also no paging support in the specification for the `PROPFIND` method and even if there was, then I would highly doubt if the Windows 10 WebDAV client would support it.

The WebDAV client in Windows 7 is terrible and it has improved a bit since Windows 10. But it has been [officially deprecated](https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features) since November 2023. Don't expect any new features for Windows WebDAV clients and you may want to move to alternative technologies.

**Comment by fiddyschmitt** [comment]
Thanks Ramon! Sad to hear it's deprecated. I really like using WebDAV because it lets me create Virtual File Systems and have the user mount them without admin rights. Do you know any alternative technologies which can do the same?

I've used Dokan and ProjFS, but both require admin rights to set up.

**Comment by ramondeklein** [comment]
No, I created NWebDAV, because I worked for a client that wanted to do document sharing and WebDAV seemed to be the most suitable option. A major advantage is that once you have the server, you can use all kind of clients to connect to it. Other options would be to offer a network drive that is using the SMB protocol (or another supported protocol). Not sure if there are open-source servers that would support it.

I do think that Microsoft will keep the WebDAV client in Windows, but disabling the service by default may already be troublesome. Enabling services typically requires administrator privileges.

**Comment by fiddyschmitt** [comment]
Thank you Ramon :) And thanks for your wonderful project.
